name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions: {}

jobs:
  release:
    uses: devantler-tech/actions/.github/workflows/create-release.yaml@94146b00945cdcc75fbd99624d909a2345d2bf67 # v10.1.1
    with:
      disable-issue-side-effects: true
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
